### ISSUE TITLE
{better-sandbox} [GUIDE] Installing the MS-Store on Sandbox

### ISSUE THREAD

**Issue by talynone** [CrazyWolf13/home-assets#1]
Thanks for better-sandbox script. With a few additions I was able to get the Windows Store app to install/run in addition to this. 

I went to:
https://store.rg-adguard.net/

And entered the following url:
https://www.microsoft.com/en-us/p/microsoft-store/9wzdncrfjbmp

From there I downloaded the following assets:
Microsoft.NET.Native.Framework.2.2_2.2.29512.0_arm64__8wekyb3d8bbwe.Appx
Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_arm64__8wekyb3d8bbwe.Appx
Microsoft.VCLibs.140.00_14.0.33519.0_arm64__8wekyb3d8bbwe.Appx
Microsoft.VCLibs.140.00.UWPDesktop_14.0.33728.0_arm64__8wekyb3d8bbwe.Appx
Microsoft.WindowsStore_22408.1401.4.0_neutral_~_8wekyb3d8bbwe.Msixbundle

Then installed them in that order.

On first run it will tell you the store is not available in your region. To fix it just change the region in Windows->Settings->Region Settings and set it to a supported region:

<img width="755" alt="image" src="https://github.com/user-attachments/assets/a3a5dda9-b0a7-49e5-92de-c979e95b4065">

After that the Windows Store runs and you can search/download/install apps!

**Comment by CrazyWolf13** [comment]
That's awesome to hear that it was helpful :)
Thanks for that info, I did not know that was possible!

Do you think this should get implemented, or was this just an addition?
Because I'm not really sure about the avaiability, as the URL's on https://store.rg-adguard.net/ seem to be only available for around 10 minutes :/

**Comment by talynone** [comment]
Up to you if you wish to try to automate it, I just wanted to document the procedure in case others wanted to do it.

**Comment by CrazyWolf13** [comment]
Oh I see, thanks again for the idea :)

But I'm sorry to say, but I don't think I'll try to add this, as it will probably be a really big amount of time to invest into getting that package downloader, as the package-links expire after 10Minutes, so I'd have to script the initial request to adguardstore too.
For the niche use case, it's probably not really worth the time, otherwise I can recommend winget source.

If you ever feel this is really an important thing, and you can give me some example use-cases, I'll reconsider. Also you are free to contribute.


Btw, thanks for sharing I'll pin this and mark it as guide, I like it :)
